function [full_grid] = MERGE_SUBGRIDS(filename_list, overlap, output_filename)
% Combines multiple subgrids generated by code using the EZ_PARALLEL
% library into a single grid.
% Input Key:
%   filename_list: List of files containing the subgrid arrays. Input
%   format is of the form
%      ['out_00000000_0000.dat'; 'out_00000000_0001.dat'; 'out_00000000_0002.dat']
%   for files out_00000000_0000.dat, out_00000000_0001.dat, and
%   out_00000000_0002.dat.
%   overlap: The ``overlap'' in your method, see the instructions for using
%   EZ_PARALLEL for further clarification.
%   output_filename: File name to output the combined grid to. For example,
%   if I wished to combine the subgrids contained in the three files
%   contained above using a timestepping method with an overlap of 1, i
%   would execute
% >> MERGE_SUBGRIDS(['out_00000000_0000.dat'; 'out_00000000_0001.dat'; 'out_00000000_0002.dat'],1, 'out_00000000.dat');
%  in the Command Window.
num_files = length(filename_list(:,1));
full_grid = readmatrix(filename_list(1,:));
for i = 2:num_files
    subgrid = readmatrix(filename_list(i,:));
    full_grid = [full_grid(1:end-overlap,:); subgrid(1+overlap:end,:)];
end

writematrix(full_grid, output_filename);
disp(['Wrote full grid to ' output_filename '.']);

end

