function [fullGrid] = MERGE_SUBGRIDS(procCount, overlap, numSteps, outputFreq)
% Combines multiple subgrids generated by code using the EZ_PARALLEL
% library into a single grid.
% Input Key:
%   - proc_count: The number of processors used for the simulation.
%   - overlap: The amount of overlap required by the time-stepping scheme.
%   - file_count: The number of output files to merge.
%   - output_freq: The number of steps between consecutive output files.

fileCount = floor(numSteps/outputFreq)+1;
for fileNum = 0:fileCount-1
   % Handle proc 0 separately.
   fileName = sprintf('out_%08d_%03d.csv', outputFreq*fileNum, 0);
   subgrid = readmatrix(fileName);
   fullGrid = subgrid(1:end,:);
   % Add all other sub-grids to full grid.
   for procId = 1:procCount-1
       fileName = sprintf('out_%08d_%03d.csv', outputFreq*fileNum, procId);
       subgrid = readmatrix(fileName);
       fullGrid = [fullGrid(1:end-overlap,:); subgrid(1+overlap:end,:)];
   end
   fullGrid = fullGrid(:,1:end-1);
   outFileName = sprintf('out_%08d.csv', outputFreq*fileNum);
   writematrix(fullGrid, outFileName);
   disp(['Wrote full grid to ' outFileName '.']);
end

end

